image: "hardwario/gcc-arm-embedded:8-2018-q4-major"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build-job:
  stage: build
  script: "make headers && make -j8"
  artifacts:
    paths:
      - openipmc-fw_CM7.bin
    expire_in: 1 month
