image: python:3.8-buster

before_script:
  - pip install mkdocs>=1.1.2

pages:
  script:
    - cd documentation
    - mkdocs build --strict --verbose
    - mv site/ ../public/
  artifacts:
    paths:
      - public
  only:
    changes:
      - documentation/*
      - .gitlab-ci.yml
      
