image: "hardwario/gcc-arm-embedded:8-2018-q4-major"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update
  - apt-get --yes install libssl-dev zlib1g-dev

build-job:
  stage: build
  script:
    - make clean
    - make -j8 hpm
  artifacts:
    paths:
      - openipmc-fw/CM4/openipmc-fw_CM4.bin
      - openipmc-fw/CM4/upgrade_CM4.hpm
      - openipmc-fw/CM7/openipmc-fw_CM7.bin
      - openipmc-fw/CM7/upgrade_CM7.hpm
    expire_in: 1 month
