#ifndef FW_METADATA_H
#define FW_METADATA_H

/*
 * METADATA FIELD DESCRIPTION
 * Version 0
 *
 * byte#  |   Size  |  Description
 *        |
 *    0   | 4 bytes |  FW_METADATA_IS_PRESENT (Magic Number). LSB first
 *    4   | 1 bytes |  Metadata field version (0x00 in this case)
 *    5   | 1 bytes |  Firmware type. Identify which firmware is this
 *    6   | 2 bytes |  Reserved
 *    8   | 4 bytes |  Image size in bytes (as generated by the linker, not including CRC appended after the image). LSB first
 */

// Position of metadata into the the image
#define FW_METADATA_ADDR 0x298

#define FW_METADATA_MAX_SIZE 360

// Magic word to confirm the presence of metadata and image
#define FW_METADATA_IS_PRESENT  0xF11B9859

// Firmware type values
#define FW_METADATA_TYPE_BOOTLOADER_CM7  1
#define FW_METADATA_TYPE_OPENIPMC_CM7    2
#define FW_METADATA_TYPE_OPENIPMC_CM4    3


#endif
