site_name: OpenIPMC-FW
site_url: https://openipmc.gitlab.io/openipmc-fw/


nav:
    - Home: index.md
    
    - 'User Guide':
        - stm32_workspace_setup.md
    
#   - About: about.md


theme: readthedocs
